CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE app_schema_version (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(100) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO app_schema_version (description)
VALUES ('backend foundation initialized');
