CREATE TABLE locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    business_type varchar(100) NOT NULL,
    address varchar(500) NOT NULL,
    latitude numeric(10, 7) NOT NULL,
    longitude numeric(10, 7) NOT NULL,
    geom geography(Point, 4326) NOT NULL,
    rent_price integer,
    memo text,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_locations_latitude CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT chk_locations_longitude CHECK (longitude >= -180 AND longitude <= 180),
    CONSTRAINT chk_locations_rent_price CHECK (rent_price IS NULL OR rent_price >= 0)
);

CREATE INDEX idx_locations_business_type ON locations (business_type);
CREATE INDEX idx_locations_keyword ON locations USING gin (to_tsvector('simple', name || ' ' || address));
CREATE INDEX idx_locations_geom ON locations USING gist (geom);

CREATE OR REPLACE FUNCTION set_location_geom()
RETURNS trigger AS $$
BEGIN
    NEW.geom = ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326)::geography;
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_locations_set_geom
BEFORE INSERT OR UPDATE OF latitude, longitude, name, business_type, address, rent_price, memo
ON locations
FOR EACH ROW
EXECUTE FUNCTION set_location_geom();
