CREATE TABLE facilities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    category varchar(100) NOT NULL,
    address varchar(500) NOT NULL,
    latitude numeric(10, 7) NOT NULL,
    longitude numeric(10, 7) NOT NULL,
    geom geography(Point, 4326) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_facilities_latitude CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT chk_facilities_longitude CHECK (longitude >= -180 AND longitude <= 180)
);

CREATE TABLE competitors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    business_type varchar(100) NOT NULL,
    address varchar(500) NOT NULL,
    latitude numeric(10, 7) NOT NULL,
    longitude numeric(10, 7) NOT NULL,
    geom geography(Point, 4326) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_competitors_latitude CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT chk_competitors_longitude CHECK (longitude >= -180 AND longitude <= 180)
);

CREATE TABLE transit_stops (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    type varchar(20) NOT NULL,
    latitude numeric(10, 7) NOT NULL,
    longitude numeric(10, 7) NOT NULL,
    geom geography(Point, 4326) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_transit_stops_type CHECK (type IN ('SUBWAY', 'BUS')),
    CONSTRAINT chk_transit_stops_latitude CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT chk_transit_stops_longitude CHECK (longitude >= -180 AND longitude <= 180)
);

CREATE TABLE foot_traffic_samples (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_date date NOT NULL,
    hour integer NOT NULL,
    latitude numeric(10, 7) NOT NULL,
    longitude numeric(10, 7) NOT NULL,
    geom geography(Point, 4326) NOT NULL,
    count integer NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_foot_traffic_samples_hour CHECK (hour >= 0 AND hour <= 23),
    CONSTRAINT chk_foot_traffic_samples_count CHECK (count >= 0),
    CONSTRAINT chk_foot_traffic_samples_latitude CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT chk_foot_traffic_samples_longitude CHECK (longitude >= -180 AND longitude <= 180)
);

CREATE INDEX idx_facilities_category ON facilities (category);
CREATE INDEX idx_facilities_geom ON facilities USING gist (geom);

CREATE INDEX idx_competitors_business_type ON competitors (business_type);
CREATE INDEX idx_competitors_geom ON competitors USING gist (geom);

CREATE INDEX idx_transit_stops_type ON transit_stops (type);
CREATE INDEX idx_transit_stops_geom ON transit_stops USING gist (geom);

CREATE INDEX idx_foot_traffic_samples_base_date_hour ON foot_traffic_samples (base_date, hour);
CREATE INDEX idx_foot_traffic_samples_geom ON foot_traffic_samples USING gist (geom);

CREATE OR REPLACE FUNCTION set_spatial_data_geom()
RETURNS trigger AS $$
BEGIN
    NEW.geom = ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326)::geography;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_facilities_set_geom
BEFORE INSERT OR UPDATE OF latitude, longitude
ON facilities
FOR EACH ROW
EXECUTE FUNCTION set_spatial_data_geom();

CREATE TRIGGER trg_competitors_set_geom
BEFORE INSERT OR UPDATE OF latitude, longitude
ON competitors
FOR EACH ROW
EXECUTE FUNCTION set_spatial_data_geom();

CREATE TRIGGER trg_transit_stops_set_geom
BEFORE INSERT OR UPDATE OF latitude, longitude
ON transit_stops
FOR EACH ROW
EXECUTE FUNCTION set_spatial_data_geom();

CREATE TRIGGER trg_foot_traffic_samples_set_geom
BEFORE INSERT OR UPDATE OF latitude, longitude
ON foot_traffic_samples
FOR EACH ROW
EXECUTE FUNCTION set_spatial_data_geom();
