CREATE TABLE location_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id bigint NOT NULL REFERENCES locations (id) ON DELETE CASCADE,
    radius_meters integer NOT NULL,
    foot_traffic_score numeric(5, 2) NOT NULL,
    transport_score numeric(5, 2) NOT NULL,
    demand_score numeric(5, 2) NOT NULL,
    competition_score numeric(5, 2) NOT NULL,
    rent_score numeric(5, 2) NOT NULL,
    total_score numeric(5, 2) NOT NULL,
    explanation text NOT NULL,
    calculated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_location_scores_radius CHECK (radius_meters > 0),
    CONSTRAINT chk_location_scores_foot_traffic CHECK (foot_traffic_score >= 0 AND foot_traffic_score <= 100),
    CONSTRAINT chk_location_scores_transport CHECK (transport_score >= 0 AND transport_score <= 100),
    CONSTRAINT chk_location_scores_demand CHECK (demand_score >= 0 AND demand_score <= 100),
    CONSTRAINT chk_location_scores_competition CHECK (competition_score >= 0 AND competition_score <= 100),
    CONSTRAINT chk_location_scores_rent CHECK (rent_score >= 0 AND rent_score <= 100),
    CONSTRAINT chk_location_scores_total CHECK (total_score >= 0 AND total_score <= 100)
);

CREATE INDEX idx_location_scores_location_calculated_at
ON location_scores (location_id, calculated_at DESC);
